name: Test API Key

on:
  push:
    branches:
      - main  # Spustí při pushnutí na větev main

jobs:
  test_api_key:
    runs-on: ubuntu-latest  # Použije Ubuntu prostředí

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run API key test
        run: |
          python -c 'import os; print(os.getenv("API_KEY"))'  # Tento kód vypíše hodnotu klíče
        env:
          API_KEY: ${{ secrets.API_KEY }}  # Použití klíče ze Secrets
